# Use an official MySQL image as the base image
FROM mysql:5.7

# Environment variables to configure MySQL (change as needed)
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=hotel_db
ENV MYSQL_USER=ubuntu
ENV MYSQL_PASSWORD=ubuntu

# Copy your MySQL database initialization script into the container
COPY ./project/hotel_db.sql /docker-entrypoint-initdb.d/

# Expose the default MySQL port (usually 3306)
EXPOSE 3306
