apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-web
  namespace: default
spec:
  maxReplicas: 11
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-app
  targetCPUUtilizationPercentage: 50
